import { IError } from './index';
export enum ERROR_USER_ENUMS {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  DATA_INVALID = 'USER_DATA_INVALID',
  WRONG_EMAIL_OR_PASSWORD = 'WRONG_EMAIL_OR_PASSWORD',
  TOKEN_NOT_PROVIDED = 'TOKEN_NOT_PROVIDED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  UNKNOWN = 'UNKNOWN',
}

export interface IErrorUsers extends IError<ERROR_USER_ENUMS> {}
