import { IError } from './index';
export enum ERROR_USERS_ENUMS {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  DATA_INVALID = 'USER_DATA_INVALID',
  EMAIL_NOT_EXISTS = 'EMAIL_NOT_EXISTS',
  WRONG_EMAIL_OR_PASSWORD = 'WRONG_EMAIL_OR_PASSWORD',

  UNKNOWN = 'UNKNOWN',
}

export interface IErrorUser extends IError<ERROR_USERS_ENUMS> {}
